// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnptigRCZLSSFoQh99NsFZTYQ8gTCOiEM',
    appId: '1:474897825201:web:f2f50ef2c1d4d16b20d190',
    messagingSenderId: '474897825201',
    projectId: 'carsharing-81beb',
    authDomain: 'carsharing-81beb.firebaseapp.com',
    storageBucket: 'carsharing-81beb.firebasestorage.app',
    measurementId: 'G-W202LBL2MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvQvPWBDKy049zDFK6_LsAAmCNtf2zQQ',
    appId: '1:474897825201:android:fd781173c0874dfc20d190',
    messagingSenderId: '474897825201',
    projectId: 'carsharing-81beb',
    storageBucket: 'carsharing-81beb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKHtn98CeT7nzFYq91E9PIRHbtWAov3d4',
    appId: '1:474897825201:ios:1caaa09196ab735220d190',
    messagingSenderId: '474897825201',
    projectId: 'carsharing-81beb',
    storageBucket: 'carsharing-81beb.firebasestorage.app',
    iosBundleId: 'com.example.carsharingKursach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKHtn98CeT7nzFYq91E9PIRHbtWAov3d4',
    appId: '1:474897825201:ios:1caaa09196ab735220d190',
    messagingSenderId: '474897825201',
    projectId: 'carsharing-81beb',
    storageBucket: 'carsharing-81beb.firebasestorage.app',
    iosBundleId: 'com.example.carsharingKursach',
  );
}
